name: myvef_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # localizations package
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  cupertino_will_pop_scope: ^1.0.4 #ios willpop
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8 #toast ui
  get: ^4.3.8 #getX
  http: ^0.13.3
  vector_math: ^2.1.0 #페인터 관련
  image_picker: ^0.8.4+2 # 기기의 카메라나 갤러리 이용
  dotted_border: ^2.0.0+1 #dot border
  sqflite: ^2.0.0+4 #로컬 db
  extended_image: ^4.2.1 #서버에있는 이미지 받아옴
  path_provider: ^2.0.1  #getDocumentDirectory... 가져옴
  flutter_local_notifications: ^9.3.3 #폰 켜져있을 때 알림
  rxdart: ^0.27.2
  permission_handler: ^8.2.5 #권한 가져오기
  percent_indicator: ^3.0.1 #퍼센트 그래프
  transparent_image: ^2.0.0
  flutter_slidable: 0.6.0 #알림페이지 리스트 스와이프
  badges: ^2.0.1 #알림에 사용할 뱃지
  flutter_app_badger: 1.3.0 #백그라운드 뱃지 카운트
  shared_preferences: ^2.0.8 # local 간단 DB
  custom_refresh_indicator: ^1.0.0 # 스크롤 상단 indicator
  firebase_messaging: ^11.1.0 #firebase
  firebase_auth: ^3.1.0 #
  firebase_core: ^1.10.0 #firebase
  dio: ^4.0.0 #form data 전송
  reorderables: ^0.4.1 # 리스트 드래그 앤 드롭
  package_info: ^2.0.2 # 로그인 유형 정보
  geolocator: ^7.7.1 #위치정보 받아오기
  screenshot: ^1.2.3 # 화면 캡쳐
  image_gallery_saver: ^1.7.1 # 갤러리에 사진 저장
  scrollable_positioned_list: ^0.2.2 # 스크롤 포지션
  jiffy: ^4.1.0 # DateTime 계산
  network_info_plus: ^2.0.2 #와이파이 정보 받아오기
  app_settings: ^4.1.1 #앱 세팅 페이지 연결
  normal: ^0.6.0 # 표준정규분포
  image_editor: ^1.0.2 # 이미지 편집

  google_sign_in: ^5.2.0 #구글 로그인
  kakao_flutter_sdk: ^0.8.2 #카카오 로그인
  json_serializable: ^6.0.1 #카카오 로그인 관련
  platform: ^3.0.2 #카카오 로그인 관련
  package_info_plus: ^1.3.0 #카카오 로그인 관련

  iamport_flutter: ^0.10.1+2 #아임포트

  sign_in_with_apple: ^3.0.0 #애플 로그인
  #app_tracking_transparency: ^2.0.2+1 #애플 추적

  firebase_dynamic_links: ^4.1.1 #동적링크
  share_plus: ^4.0.3 #공유하기
  store_redirect: ^2.0.1 #store 열기

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/image/
    - assets/image/bowl/
    - assets/image/Login/
    - assets/image/Global/
    - assets/image/nav_bar/
    - assets/image/dash_board/
    - assets/image/community/
    - assets/image/graph/
    - assets/text/
    - assets/config/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/font/SpoqaHanSansNeo-Regular.ttf
        - asset: assets/font/SpoqaHanSansNeo-Medium.ttf
          weight: 500
        - asset: assets/font/SpoqaHanSansNeo-Bold.ttf
          weight: 700

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
