const String svgVfLogoAndText = 'assets/image/Global/vfLogoAndText.svg'; // 마이베프 로고 & 텍스트
const String svgVfLogo = 'assets/image/Global/vfLogo.svg'; // 마이베프 로고
const String svgBackArrow = 'assets/image/Global/backArrowIcon.svg'; // 뒤로가기 아이콘
const String svgCancelIcon = 'assets/image/Global/cancelIcon.svg'; // X 모양 취소 아이콘
const String svgRightArrow = 'assets/image/Global/rightArrowIcon.svg'; // 오른쪽 화살표 아이콘
const String svgArrowDown = 'assets/image/Global/arrowDown.svg'; // 아래 화살표 아이콘
const String svgArrowUp = 'assets/image/Global/arrowUp.svg'; // 위 화살표 아이콘
const String svgRightArrowSmall = 'assets/image/Global/rightArrowSmallIcon.svg'; // 오른쪽 작은 화살표 아이콘
const String svgMagnifyingGlassGray = 'assets/image/Global/magnifyingGlassIconGray.svg'; // 회색 검색 아이콘
const String svgMagnifyingGlassBlack = 'assets/image/Global/magnifyingGlassIconBlack.svg'; // 검정색 검색 아이콘
const String svgDogAndCat = 'assets/image/Global/dogAndCat.svg'; // 강아지와 고양이 아이콘
const String svgCameraIcon = 'assets/image/Global/cameraIcon.svg'; // 카메라 아이콘
const String svgPictureIcon = 'assets/image/Global/pictureIcon.svg'; // 사진 아이콘
const String svgWhiteCancelIcon = 'assets/image/Global/whiteCancelIcon.svg'; // 그라데이션 취소 아이콘
const String svgPetPhotoDefault = 'assets/image/Global/vfPetPhotoDefault.svg'; //펫 프로필 디폴드 사진
const String svgHeartIcon = 'assets/image/community/heartIcon.svg'; // 하트 아이콘
const String svgReplyIcon = 'assets/image/community/replyIcon.svg'; // 댓글 아이콘
const String svgHorizontalThreeDot = 'assets/image/community/horizontalThreeDot.svg'; // 점 셋 (가로)
const String svgVerticalThreeDot = 'assets/image/community/verticalThreeDot.svg'; // 점 셋 (세로)
const String svgPetAddIcon = 'assets/image/Global/petAddIcon.svg'; // + 아이콘
const String svgReorderIcon = 'assets/image/Global/reorderIcon.svg'; // 순서 변경 아이콘
const String svgRemoveGrayIcon = 'assets/image/Global/removeGrayIcon.svg'; // X 모양 회색 삭제 아이콘
const String svgRemoveWhiteIcon = 'assets/image/Global/removeWhiteIcon.svg'; // X 모양 흰색 삭제 아이콘
const String svgFilterAddIcon = 'assets/image/community/filterAddIcon.svg'; // 필터에 들어가는 add 아이콘
const String svgVfUserDefaultImg = 'assets/image/Global/vfUserDefaultImage.svg'; // 유저 기본 이미지
const String svgCircleCheck = 'assets/image/Global/circleCheck.svg'; // 동그라미 체크 버튼 (체크)
const String svgCircleUncheck = 'assets/image/Global/circleUncheck.svg'; // 동그라미 체크 버튼 (체크 x)
const String svgLogout = 'assets/image/Global/logout.svg'; // 로그아웃 아이콘
const String svgOpenedEyeIcon = 'assets/image/Global/openedEyeIcon.svg'; // 눈 뜬 아이콘
const String svgClosedEyeIcon = 'assets/image/Global/closedEyeIcon.svg'; // 눈 감은 아이콘
const String svgFootIcon = 'assets/image/Global/footIcon.svg'; // 발바닥 아이콘
const String svgWeightIcon = 'assets/image/Global/weightIcon.svg'; // 몸무게 아이콘
const String svgSexIcon = 'assets/image/Global/sexIcon.svg'; // 성별 아이콘
const String svgAgeIcon = 'assets/image/Global/ageIcon.svg'; // 나이 아이콘
const String svgFoodStyleIcon = 'assets/image/Global/foodStyleIcon.svg'; // 먹스타일 아이콘
const String svgInitializationIcon = 'assets/image/Global/initializationIcon.svg'; // 초기화 아이콘
const String svgRedBatteryIcon = 'assets/image/Global/redBatteryIcon.svg'; // 빨간 배터리 아이콘
const String svgGreyBatterIcon = 'assets/image/Global/greyBatteryIcon.svg'; // 회색 배터리 아이콘
const String svgPramBodyGoodState = 'assets/image/Global/prambodygoodstate.svg'; // 프람 상태 안 좋음 - 몸통 포함
const String svgBetiHeadBadState = 'assets/image/Global/betiheadbadstate.svg'; // 베티 상태 좋음 - 머리만
const String svgBetiBodyBadState = 'assets/image/Global/betibodybadstate.svg'; // 베티 상태 좋음 - 몸통 포함
const String svgQuestionInCircle = 'assets/image/dash_board/questionInCircle.svg'; // 물음표 아이콘
const String svgTailIcon = 'assets/image/dash_board/tailIcon.svg'; // 돼지 꼬리 아이콘
const String svgBowlBottom = 'assets/image/bowl/bowlBottom.png'; // 보울 하부
const String svgBowlBottomDetail = 'assets/image/bowl/bowlBottomDetail.png'; // 보울 하부 설명
const String svgBowlBottomWithButton = 'assets/image/bowl/bowlBottomWithButton.png'; // 보울 하부 버튼
const String svgBowlFront = 'assets/image/bowl/bowlFront.png'; // 보울 전면
const String svgBowl = 'assets/image/bowl/bowl.png'; // 보울
const String svgSettingIcon = 'assets/image/dash_board/settingIcon.svg';  //설정